# Generated by Django 5.1.7 on 2025-09-01 05:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Etiqueta')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='KanbanColumna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de la columna en el tablero.')),
            ],
            options={
                'verbose_name': 'Columna Kanban',
                'verbose_name_plural': 'Columnas Kanban',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Trabajador')),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, help_text='Formato: +521234567890', max_length=17, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='KanbanTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de la tarea dentro de la columna.')),
                ('columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='ventas.kanbancolumna')),
            ],
            options={
                'verbose_name': 'Tarea Kanban',
                'verbose_name_plural': 'Tareas Kanban',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Introduce el número de teléfono con código de país, ej: +1 (555) 123-4567', max_length=25)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('NUEVO', 'Prospecto Inicial'), ('CONTACTADO', 'Primer Contacto'), ('CALIFICANDO', 'En Negociación'), ('GANADO', 'Cliente Cerrado'), ('PERDIDO', 'Rechazado')], default='NUEVO', max_length=20)),
                ('interes_principal', models.CharField(choices=[('IMPORTACION', 'Importación'), ('EXPORTACION', 'Exportación'), ('AMBOS', 'Ambos'), ('OTRO', 'Otro')], default='IMPORTACION', max_length=20, verbose_name='Interés Principal')),
                ('referencio', models.CharField(blank=True, help_text="¿Cómo llegó este prospecto a nosotros? (ej: 'Cliente X', 'Evento Y')", max_length=150, verbose_name='Referido por')),
                ('contacto_referencio', models.CharField(blank=True, help_text='Persona específica que lo refirió.', max_length=150, verbose_name='Contacto de Referencia')),
                ('interes_cliente', models.TextField(blank=True, help_text='Describe los productos o servicios de interés del prospecto.', verbose_name='Detalles del Interés del Cliente')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos', to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ManyToManyField(blank=True, to='ventas.etiqueta')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LLAMADA', 'Llamada'), ('CORREO', 'Correo'), ('REUNION', 'Reunión'), ('OTRO', 'Otro')], max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='ventas.prospecto')),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Título del Archivo')),
                ('archivo', models.FileField(upload_to='archivos_adjuntos/%Y/%m/', verbose_name='Archivo Adjunto')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='ventas.prospecto')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('planificacion', models.TextField(blank=True, help_text='Detalles, alcance y objetivos iniciales del proyecto.', verbose_name='Planificación')),
                ('cierre_proyecto', models.TextField(blank=True, help_text='Resumen, resultados finales y lecciones aprendidas.', verbose_name='Cierre del Proyecto')),
                ('prospecto', models.OneToOneField(limit_choices_to={'estado': 'GANADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='ventas.prospecto')),
            ],
        ),
        migrations.AddField(
            model_name='kanbancolumna',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_columnas', to='ventas.proyecto'),
        ),
        migrations.CreateModel(
            name='EquipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(help_text='Ej: Líder de Proyecto, Desarrollador, etc.', max_length=100)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.proyecto')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.trabajador')),
            ],
            options={
                'unique_together': {('proyecto', 'trabajador')},
            },
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='ventas.proyecto')),
            ],
            options={
                'ordering': ['fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='DiagramaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('codigo', models.TextField(help_text='Código del diagrama en formato JSON (JointJS)')),
                ('svg_representation', models.TextField(blank=True, help_text='El código SVG del diagrama para la exportación a PDF.', verbose_name='Representación SVG')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagramas', to='ventas.proyecto')),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_recordatorio', models.DateTimeField()),
                ('completado', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_creados', to=settings.AUTH_USER_MODEL)),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='ventas.prospecto')),
            ],
            options={
                'ordering': ['-fecha_recordatorio'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField()),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_proyecto', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='ventas.proyecto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='equipo',
            field=models.ManyToManyField(related_name='proyectos_asignados', through='ventas.EquipoProyecto', to='ventas.trabajador'),
        ),
        migrations.CreateModel(
            name='ProspectoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, '⭐ Malo'), (2, '⭐⭐ Regular'), (3, '⭐⭐⭐ Bueno'), (4, '⭐⭐⭐⭐ Muy Bueno'), (5, '⭐⭐⭐⭐⭐ Excelente')], default=3, verbose_name='Calificación')),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.prospecto')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'ordering': ['prospecto', 'trabajador'],
                'unique_together': {('prospecto', 'trabajador')},
            },
        ),
        migrations.AddField(
            model_name='prospecto',
            name='trabajadores',
            field=models.ManyToManyField(related_name='prospectos', through='ventas.ProspectoTrabajador', to='ventas.trabajador', verbose_name='Trabajadores de Contacto'),
        ),
    ]
