# Generated by Django 5.1.7 on 2025-08-19 05:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Trabajador')),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('NUEVO', 'Prospecto Inicial'), ('CONTACTADO', 'Primer Contacto'), ('CALIFICANDO', 'En Negociación'), ('GANADO', 'Cliente Cerrado'), ('PERDIDO', 'Rechazado')], default='NUEVO', max_length=20)),
                ('referencio', models.CharField(blank=True, max_length=150, verbose_name='Referido por')),
                ('contacto_referencio', models.CharField(blank=True, max_length=150, verbose_name='Contacto de Referencia')),
                ('interes_principal', models.CharField(choices=[('IMPORTACION', 'Importación'), ('EXPORTACION', 'Exportación'), ('AMBOS', 'Ambos'), ('OTRO', 'Otro')], default='IMPORTACION', max_length=20, verbose_name='Interés Principal')),
                ('interes_cliente', models.TextField(blank=True, verbose_name='Detalles del Interés del Cliente')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos', to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ManyToManyField(blank=True, to='ventas.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LLAMADA', 'Llamada'), ('CORREO', 'Correo'), ('REUNION', 'Reunión'), ('OTRO', 'Otro')], max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='ventas.prospecto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_recordatorio', models.DateTimeField()),
                ('completado', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_creados', to=settings.AUTH_USER_MODEL)),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='ventas.prospecto')),
            ],
            options={
                'ordering': ['-fecha_recordatorio'],
            },
        ),
        migrations.CreateModel(
            name='ProspectoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, '⭐ Malo'), (2, '⭐⭐ Regular'), (3, '⭐⭐⭐ Bueno'), (4, '⭐⭐⭐⭐ Muy Bueno'), (5, '⭐⭐⭐⭐⭐ Excelente')], default=3, verbose_name='Calificación')),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.prospecto')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'unique_together': {('prospecto', 'trabajador')},
            },
        ),
        migrations.AddField(
            model_name='prospecto',
            name='trabajadores',
            field=models.ManyToManyField(related_name='prospectos', through='ventas.ProspectoTrabajador', to='ventas.trabajador', verbose_name='Trabajadores de Contacto'),
        ),
    ]
