# Generated by Django 5.1.7 on 2025-08-26 05:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etiqueta',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='interaccion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Interacción', 'verbose_name_plural': 'Interacciones'},
        ),
        migrations.AlterModelOptions(
            name='prospecto',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='prospectotrabajador',
            options={'ordering': ['prospecto', 'trabajador']},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['nombre'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='contacto_referencio',
            field=models.CharField(blank=True, help_text='Persona específica que lo refirió.', max_length=150, verbose_name='Contacto de Referencia'),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='interes_cliente',
            field=models.TextField(blank=True, help_text='Describe los productos o servicios de interés del prospecto.', verbose_name='Detalles del Interés del Cliente'),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='referencio',
            field=models.CharField(blank=True, help_text="¿Cómo llegó este prospecto a nosotros? (ej: 'Cliente X', 'Evento Y')", max_length=150, verbose_name='Referido por'),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='telefono',
            field=models.CharField(blank=True, help_text='Introduce el número de teléfono con código de país, ej: +1 (555) 123-4567', max_length=25),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono',
            field=models.CharField(blank=True, help_text='Formato: +521234567890', max_length=17, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Título del Archivo')),
                ('archivo', models.FileField(upload_to='media/', verbose_name='Archivo Adjunto')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='ventas.prospecto')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
