# Generated by Django 5.1.7 on 2025-09-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancolumna',
            name='icono',
            field=models.CharField(blank=True, help_text="Clase de Font Awesome (ej: 'fas fa-check-circle').", max_length=50),
        ),
    ]
