# Generated by Django 5.1.7 on 2025-08-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_etiqueta_options_alter_interaccion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoadjunto',
            name='archivo',
            field=models.FileField(upload_to='', verbose_name='Archivo Adjunto'),
        ),
    ]
