# Generated by Django 5.1.7 on 2025-08-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_archivoadjunto_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoadjunto',
            name='archivo',
            field=models.FileField(upload_to='', verbose_name='Archivo Adjunto'),
        ),
    ]
