# Generated by Django 5.1.7 on 2025-08-31 16:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_archivoadjunto_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoadjunto',
            name='archivo',
            field=models.FileField(upload_to='archivos_adjuntos/%Y/%m/', verbose_name='Archivo Adjunto'),
        ),
        migrations.CreateModel(
            name='EquipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(help_text='Ej: Líder de Proyecto, Desarrollador, etc.', max_length=100)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('planificacion', models.TextField(blank=True, help_text='Detalles, alcance y objetivos iniciales del proyecto.', verbose_name='Planificación')),
                ('cierre_proyecto', models.TextField(blank=True, help_text='Resumen, resultados finales y lecciones aprendidas.', verbose_name='Cierre del Proyecto')),
                ('equipo', models.ManyToManyField(related_name='proyectos_asignados', through='ventas.EquipoProyecto', to='ventas.trabajador')),
                ('prospecto', models.OneToOneField(limit_choices_to={'estado': 'GANADO'}, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='ventas.prospecto')),
            ],
        ),
        migrations.AddField(
            model_name='equipoproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.proyecto'),
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='ventas.proyecto')),
            ],
            options={
                'ordering': ['fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField()),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_proyecto', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='ventas.proyecto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='equipoproyecto',
            unique_together={('proyecto', 'trabajador')},
        ),
    ]
