# Generated by Django 5.1.7 on 2025-09-01 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_archivoadjunto_archivo_equipoproyecto_proyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('codigo', models.TextField(help_text='Código del diagrama, por ejemplo, en sintaxis Mermaid.js')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagramas', to='ventas.proyecto')),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='KanbanColumna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de la columna en el tablero.')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_columnas', to='ventas.proyecto')),
            ],
            options={
                'verbose_name': 'Columna Kanban',
                'verbose_name_plural': 'Columnas Kanban',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='KanbanTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de la tarea dentro de la columna.')),
                ('columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='ventas.kanbancolumna')),
            ],
            options={
                'verbose_name': 'Tarea Kanban',
                'verbose_name_plural': 'Tareas Kanban',
                'ordering': ['orden'],
            },
        ),
    ]
