# Generated by Django 5.1.7 on 2025-09-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_diagramaproyecto_kanbancolumna_kanbantarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagramaproyecto',
            name='svg_representation',
            field=models.TextField(blank=True, help_text='El código SVG del diagrama para la exportación a PDF.', verbose_name='Representación SVG'),
        ),
        migrations.AlterField(
            model_name='diagramaproyecto',
            name='codigo',
            field=models.TextField(help_text='Código del diagrama en formato JSON (JointJS)'),
        ),
    ]
