# Generated by Django 5.1.7 on 2025-09-01 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_proyecto_diagrama_flujo_data_kanbancolumna_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='diagrama_flujo_data',
        ),
    ]
